export const ALL_SONGS_REQUEST = "ALL_SONGS_REQUEST";
export const ALL_SONGS_SUCCESS = "ALL_SONGS_SUCCESS";
export const ALL_SONGS_FAIL = "ALL_SONGS_FAIL";

export const SONGS_DELETE_REQUEST = "SONGS_DELETE_REQUEST";
export const SONGS_DELETE_SUCCESS = "SONGS_DELETE_SUCCESS";
export const SONGS_DELETE_FAIL = "SONGS_DELETE_FAIL";