export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_DONE = "USER_REGISTER_DONE";

export const GET_USER_REQUEST = "USER_LOGIN_REQUEST";
export const GET_USER_SUCCESS = "USER_LOGIN_SUCCESS";
export const GET_USER_FAIL = "USER_LOGIN_FAIL";
export const GET_USER_LOGOUT = "USER_LOGOUT";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const USER_EDIT_REQUEST = "USERS_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USERS_EDIT_SUCCESS";
export const USER_EDIT_FAIL = "USERS_EDIT_FAIL";
export const USER_EDIT_DONE = "USER_EDIT_DONE";

export const USER_DELETE_REQUEST = "USERS_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USERS_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USERS_DELETE_FAIL";